import { GetParameterCommand, SSM } from "@aws-sdk/client-ssm"
import { writeFile } from "node:fs/promises"

import { STAGE } from "../src/constants"

const client = new SSM()

export const injectEnvironment = async () => {
	const parameter = await client.send(
		new GetParameterCommand({
			Name: `/manager/${STAGE}/environment`,
			WithDecryption: true,
		}),
	)

	if (!parameter.Parameter?.Value) {
		return
	}

	// @ts-expect-error - No idea why this is happening
	const environment = JSON.parse(parameter.Parameter.Value.toString("utf8"))

	environment.NEXTAUTH_URL = `http://localhost:3000`

	const dotenv = Object.entries(environment)
		.map(([key, value]) => `${key}=${value}`)
		.join("\n")

	await writeFile(
		".env.local",
		`# THIS FILE WAS AUTOGENERATED AT ${new Date().toISOString()}\n${dotenv}`,
	)
}

void injectEnvironment()
