import { GetParameterCommand, SSM } from "@aws-sdk/client-ssm"
import { writeFile } from "node:fs/promises"

import { STAGE } from "../src/constants"

const client = new SSM()

export const injectEnvironment = async () => {
	const parameter = await client.send(
		new GetParameterCommand({
			Name: `/${STAGE}/manager/environment`,
		}),
	)

	if (!parameter.Parameter?.Value) {
		return
	}

	const environment = JSON.parse(parameter.Parameter.Value)

	const dotenv = Object.entries(environment)
		.map(([key, value]) => `${key}=${value}`)
		.join("\n")

	await writeFile(
		".env.local",
		`# THIS FILE WAS AUTOGENERATED AT ${new Date().toISOString()}\n${dotenv}`,
	)
}

void injectEnvironment()
